export const majorList = [
  "Agriculture",
  "Food Sciences & Technology",
  "Environmental Science",
  "Architecture",
  "City/Urban/Regional Planning",
  "Landscape Architecture",
  "Area Studies",
  "Art",
  "Art History, Criticism & Conservation",
  "Dance",
  "Cinema/Film",
  "Cinematography/Film/Vide Production",
  "Graphic Design",
  "Fashion/Apparel Design",
  "Industrial Design",
  "Music",
  "Theatre Arts/Drama",
  "Photography",
  "Accounting",
  "Hotel/Motel Management",
  "Human Resources Management",
  "Restaurant/Food Services Management",
  "Finance",
  "Tourism & Travel Marketing",
  "Sales, Merchandising, & Marketing, General",
  "Communications",
  "Advertising",
  "Journalism",
  "Family & Consumer Sciences",
  "Food & Nutrition",
  "Sport & Fitness Administration/Management",
  "Computer Networking",
  "Computer Science",
  "Computer System Administration",
  "Mathematics",
  "Applied Mathematics",
  "Statistics",
  "Education",
  "Bioengineering",
  "Architectural Engineering",
  "Computer Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Biomedical Engineering",
  "Electrical, Electronics",
  "Industrial Engineering",
  "Mechanical Engineering",
  "Nuclear Engineering",
  "English Language",
  "Foreign Languages",
  "French Language",
  "Asian Languages",
  "German Language",
  "Linguistics",
  "Spanish Language",
  "Middle Eastern Languages",
  "Hospital/Facilities Administration",
  "Philosophy",
  "Biology",
  "Biochemistry & Biophysics",
  "Ecology",
  "Zoology",
  "Physics",
  "Astronomy",
  "Chemistry",
  "Economics",
  "Law",
  "Anthropology",
  "Criminology",
  "Geography",
  "History",
  "Political Science",
  "Urban Studies/Urban Affairs",
  "Psychology",
  "Others",
  "None"
];